### PR TITLE
Implemented PE698 Brand CSV Export

### PR DESCRIPTION
**Pull request by nikita-pardeshi-github**

### CODE REVIEW

**Review by Chris33871 — DISMISSED** [review]
Hi @nikita-pardeshi-github ,

The format for the CSV doesn't work. The headers are all in the same column whilst some row entries are in different columns.
Screenshot 2023-10-25 121147

Also, would there be a potential clash with Ahmed's PR? The button he's implementing is in the same position as yours. Not sure how Django works there so just pointing that out.

**Comment by nikita-pardeshi-github** [comment]
> Hi @nikita-pardeshi-github ,
> 
> The format for the CSV doesn't work. The headers are all in the same column whilst some row entries are in different columns. Screenshot 2023-10-25 121147
> 
> Also, would there be a potential clash with Ahmed's PR? The button he's implementing is in the same position as yours. Not sure how Django works there so just pointing that out.

Hi @Chris33871

**Comment by RogerTangos** [comment]
LGTM. There are some conflicts because I already merged Ahmed's PR. Please resolve and then merge :)

**Review by RogerTangos — APPROVED** [review]

**Comment by RogerTangos** [comment]
On a general note, I think that this could be done a bit more elegantly by moving some of these utility functions out of `brand/views.py` and iterating through the Commentary properties instead of explicitly listing them out. Both of those are things that you can do @nikita-pardeshi-github , if you want some practice... but I'm also ok to merge without it.

**Comment by nikita-pardeshi-github** [comment]
> On a general note, I think that this could be done a bit more elegantly by moving some of these utility functions out of `brand/views.py` and iterating through the Commentary properties instead of explicitly listing them out. Both of those are things that you can do @nikita-pardeshi-github , if you want some practice... but I'm also ok to merge without it.

Thanks Albert for reviewing it. I really appreciate your suggestion. Yes, I will implement that way and then push my changes.

**Comment by RogerTangos** [comment]
Just DM'd Nikita directly. The code works and can be merged, or Nikita can work on it some more if she'd like

**Comment by nikita-pardeshi-github** [comment]
Yes, I would like to work on it. As Albert suggested, I will make use of serializer model of django and try to write in better way. Once again thanks Albert for your suggestions.

**Pull request merged**
