### PR TITLE
PE-491 Run script to identify likely bank duplicates 

### PR DESCRIPTION
**Pull request by ahmedlamidi**

### CODE REVIEW

**Comment by nikita-pardeshi-github** [comment]
image

image

**Review by Chris33871 — COMMENTED** [review]
Hi @ahmedlamidi , 

Thank you for the PR. It looks really good. 

A couple of things:
- Please provide a description when making a PR, it goes a long way. Especially with a ticket like this one

- The feature works but can be improved. Duplicates show well but if ACD is a possible duplicate of ABC then it will also show ABC as a possible duplicate of ACD.
That example itself doesn't pose a problem but when you have EBS as a possible duplicate of CBS, TBS, KCB, JBS, etc. You will also have all those banks be possible duplicates of one another. Making it so that each duplicate has a reverse duplicate.
The duplicate list provided looks like it might be 9 times longer than it needs to be.

I reckon this is happening because of the nested for loop in check_duplicates.py. On a larger database, this could be quite problematic. I would have to look into this deeper but I think it might be possible to reduce the time complexity and avoid having repeating duplicates.


https://github.com/bank-green/bankgreen-django/assets/68507104/c98418f4-3917-4d1a-a893-2c46439d752b


Once again, I want to reiterate; the code works well and if Albert doesn't see a problem with the repeating duplicates then it can safely be merged 👍

**Comment by PooriaT** [comment]
Hi @ahmedlamidi 

Thanks a lot for your PR.  Just like what @nikita-pardeshi-github suggested, using the relative path might be a better idea. It could help avoid problems if, for example, we decide to rename something. Also, you put two libraries in admin.py, which have not been used. If they are not required, they can be omitted for optimisation.

**Review by Chris33871 — APPROVED** [review]
Hi @ahmedlamidi ,

This looks good. It seems like the brands are not duplicating the duplicates. 

I'll let someone else make a final check and then I belive this can be merged

**Review by RogerTangos — APPROVED** [review]
LGTM

**Comment by RogerTangos** [comment]
merged and deployed :)

**Pull request merged**
