### PR TITLE
Features

### PR DESCRIPTION
**Pull request by RogerTangos**
This makes the implementation of features generic. Users can add individual feature types, and then add BrandFeatures of that feature type to existing brands. This was a highly requested... feature... from bank.green and switchit staff

- creates new records: 
  - FeatureType, FeatureAvailabilityChoice, BrandFeature
- Migrates existing data to these new records
  - Migration should run correctly if run on a clean project, hence the `try except` block
  - Unfortunately, this means that the feature model cannot be fully removed until the next pr
- Deprecates but does not remove feature model (otherwise the data migration would not work)

- brand/schema.py is still running existing features and needs updating to support new records. @shuesken, since you know this a bit better, would you please update schema.py to support both the depreciated features and the new records, so that the frontend migration can be seamless?

### CODE REVIEW

**Comment by RogerTangos** [comment]
I'm a bit confused by the failing tests. This is running on my system with identical files. Maybe it's caching?

**Comment by shuesken** [comment]
I made two commits; the first fixes the test, the second adds GraphQL support. See my comment after for general thoughts on this PR.
```
{
  brand(tag: "gls_bank") {
    features {
      onlineBanking
    }
    bankFeatures {
    	offered,
      feature {
        name,
        description
      }
    }
  }
}
```
will yield
```
{
  "data": {
    "brand": {
      "features": {
        "onlineBanking": true
      },
      "bankFeatures": [
        {
          "offered": "YES",
          "feature": {
            "name": "checking",
            "description": "Does the bank provide checkings accounts?"
          }
        },
        {
          "offered": "YES",
          "feature": {
            "name": "saving",
            "description": "Does the bank provide savings accounts?"
          }
        },
        {
          "offered": "N_A",
          "feature": {
            "name": "interest_rates",
            "description": "Details about the bank's interest rates?"
          }
        },
        {
          "offered": "YES",
          "feature": {
            "name": "free_atm_withdrawal",
            "description": "Does the bank provide free ATM withdrawals?"
          }
        },
        {
          "offered": "YES",
          "feature": {
            "name": "online_banking",
            "description": "Does the bank provide online banking?"
          }
        },
        {
          "offered": "YES",
          "feature": {
            "name": "mortgage_or_loans",
            "description": "Does the bank provide mortgages or loans?"
          }
        },
        {
          "offered": "YES",
          "feature": {
            "name": "deposit_protection",
            "description": "Details about the bank's deposit protection"
          }
        },
        {
          "offered": "YES",
          "feature": {
            "name": "credit_cards",
            "description": "Does the bank provide credit cards?"
          }
        }
      ]
    }
  }
}
```

**Comment by shuesken** [comment]
Props on the smooth migration @RogerTangos! I for sure thought this would break the DB on my machine :D

### DB Model
I think the model as proposed has too much leeway. It for example allows a `Brand` to have a `BankFeature` with the identical `FeatureType` and identical `applicable_countries` twice, but with different values for `offered`. I think each bank should only be able to implement each feature exactly once (or at least only once per country).

To achieve this, we could use a ManyToMany relationship from `Brand` to `FeatureType` mediated through a model (similar to the existing `BrandFeature`) that adds the additional fields as described here: https://docs.djangoproject.com/en/4.0/topics/db/models/#intermediary-manytomany

I suspect the current model was chosen to accomodate having different features available in different countries. I believe this adds unjustified complexity and we should just use `offered = "maybe"` for these cases, the same way we would for a feature that's only offered to 18-27 year olds. I'm open to being convinced the other way if the case is very common; e.g. Deutsche Bank having significantly different features in its EU operation than its US one. In that case, the intermediating model could handle the distinction (and the precise way we'll have to decide on). I think this will make for ugly admin panels though if we stick with the defaults. If we're heading towards externally consumable API (which this PR is), then butchering our data model in favour of easier administration via Django default admin forms is I think no longer a good tradeoff to make though.

### Other notes
I think `FeatureAvailabilityChoice` should have the same style of code as `ResultPageVariationChoice` and `RatingChoice`. I think the different ways of defining a choice field are mostly equivalent, but I worry they subtly affect how e.g. Graphene will serialize things.

I also think `FeatureAvailabilityChoice` could be trimmed down; `"Unknown"` could be expressed by that feature simply not appearing in the database, and `"somewhat"` and `"maybe"` seem identical for all practical purposes.

**Comment by RogerTangos** [comment]
I'm coming around to the idea of removing available countries from features. Indeed, a better way to manage the case of deutsche bank, for example, is to have a deutsche_bank_de, another deutsche_bank_us, and another deutsche_bank, and then to implement feature inheritance. For the time being, bank.green can just use the top level DB.

**Comment by shuesken** [comment]
Great I'll get on that :)

**Comment by RogerTangos** [comment]
Updated and ready for review, @shuesken. Any chance we could get this in this weekend and update the site? Then we can get a virtual assistant onto the task of populating the brands

**Comment by shuesken** [comment]
Removed applicable_countries from admin view, made BrandFeature unique across Brand & FeatureType (rather than defining it as a ManyToManyField, same effect), and fixed the migration to not try to create applicable countries.

Deployed and running.

**Pull request merged**
